# experiment name
EXP_NAME: SwinIRNet_default_sr_x4-DFO2K
# random number seed
SEED: 0
# super resolution magnification factor
SCALE: 4
# run device model
DEVICE_ID: 0

# Model define
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: False
  G:
    NAME: swinir_default_sr_x4
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    COMPILED: False

TRAIN:
  DATASET:
    TRAIN_GT_IMAGES_DIR: ./datasets/DFO2K

    GT_IMAGE_SIZE: 192

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    PRETRAINED_G_MODEL: ""
    RESUMED_G_MODEL: ""

  # training hyperparameters
  HYP:
    IMGS_PER_BATCH: 32
    SHUFFLE: True
    NUM_WORKERS: 12
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

    EPOCHS: 100

  OPTIM:
    NAME: Adam
    LR: 0.0002
    BETAS: [0.9, 0.999]
    EPS: 0.0001
    WEIGHT_DECAY: 0.0

  LR_SCHEDULER:
    NAME: MultiStepLR
    MILESTONES: [ 500, 800, 900, 950 ]
    GAMMA: 0.5

  # Loss function
  LOSSES:
    PIXEL_LOSS:
      NAME: L1Loss
      WEIGHT: [1.0]

  PRINT_FREQ: 100

TEST:
  DATASET:
    PAIRED_TEST_GT_IMAGES_DIR: "./datasets/Set5/GTmod12"
    PAIRED_TEST_LR_IMAGES_DIR: "./datasets/Set5/LRbicx4"

  # Test hyperparameters
  HYP:
    IMGS_PER_BATCH: 1
    SHUFFLE: False
    NUM_WORKERS: 1
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  # Only test Y channel
  ONLY_TEST_Y_CHANNEL: True

  SAVE_IMAGE: False
  SAVE_DIR_PATH: None
