_BASE_: "../degradation_model.yaml"

DEVICE: "0" # "0" means GPU 0, "0,1" means GPU 0 and 1, etc.
EXP_NAME: "realesrgan_x4-df2k_degradation" # Name of the experiment
PHASE: "gan" # psnr, gan
UPSCALE_FACTOR: 4

DATASET:
  TRAIN_GT_IMAGES_DIR: "datasets/DFO2K/DFO2K_sub_image_384x384"  # 178574 images
  TRAIN_LR_IMAGES_DIR: ""

  VAL_GT_IMAGES_DIR: "datasets/Set5/GTmod12"
  VAL_LR_IMAGES_DIR: "datasets/Set5/LRbicx4"

MODEL:
  G:
    TYPE: "rrdbnet_x4"
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    GROWTH_CHANNELS: 32
    NUM_RRDB: 23
  D:
    TYPE: "discriminator_for_unet"
    IN_CHANNELS: 3
    OUT_CHANNELS: 1
    CHANNELS: 64
    UPSAMPLE_METHOD: "bilinear"

TRAIN:
  RESUME_G: "./results/train/realesrgan_x4-df2k_degradation1/weights/g_last_checkpoint.pkl"
  RESUME_D: "./results/train/realesrgan_x4-df2k_degradation1/weights/d_last_checkpoint.pkl"

  # train weights
  G_WEIGHTS_PATH: ""
  D_WEIGHTS_PATH: ""

  # train datasets
  IMAGE_SIZE: 256
  BATCH_SIZE: 32  # 178574 / 16 ~= 11160 iters / epoch
  NUM_WORKERS: 12

  # train solver
  SOLVER:
    G:
      OPTIM:
        TYPE: "adam"
        LR: 0.0001
        BETAS: [ 0.9, 0.99 ]

      LR_SCHEDULER:
        TYPE: "constant"
        FACTOR: 1.0
        TOTAL_ITERS: 36
    D:
      OPTIM:
        TYPE: "adam"
        LR: 0.0001
        BETAS: [ 0.9, 0.99 ]

      LR_SCHEDULER:
        TYPE: "constant"
        FACTOR: 1.0
        TOTAL_ITERS: 36

  # loss config
  LOSS:
    PIXEL:
      TYPE: "l1_loss"
      WEIGHT: 1.0
    FEATURE:
      TYPE: "feature_loss"
      ARCH_NAME: "vgg19"
      LAYER_WEIGHT_DICT:
        "conv1_2": 0.1
        "conv2_2": 0.1
        "conv3_4": 1.0
        "conv4_4": 1.0
        "conv5_4": 1.0
      NORMALIZE: True
    ADV:
      TYPE: "bce_with_logits_loss"
      WEIGHT: 0.1

  # train hyper-parameters
  EPOCHS: 5  # 36 * 11160 = 401,760 ~= 400,000 iters

  # train setup
  LOCAL_RANK: -1
  RANK: -1
  WORLD_SIZE: 1
  DIST_URL: "env://"

  # train results
  OUTPUT_DIR: "results/train"
  VERBOSE: True

EVAL:
  WEIGHTS_PATH: "results/train/realesrgan_x4-df2k_degradation/weights/g_best_checkpoint.pkl"
  NIQE_WEIGHTS_PATH: "results/pretrained_models/niqe_model.mat"
  ONLY_TEST_Y_CHANNEL: True